TIMEFRAME_TRIGGER = "15m"
TIMEFRAME_CONFIRM = "30m"
TIMEFRAME_TREND = "1h"
TIMEFRAME_CONTEXT = "4h"

SIDE_LONG = "LONG"
SIDE_SHORT = "SHORT"
SIDE_NONE = "NONE"

SIGNAL_DIRECT = "DIRECT"
SIGNAL_PROBE = "PROBE"
SIGNAL_WAIT = "WAIT"
SIGNAL_NO_TRADE = "NO_TRADE"
